### Register - valid request
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "correctUsername",
    "password": "correctPassword",
    "confirmPassword": "correctPassword"
}

### Register - invalid request
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "correctUsername",
    "password": "invpswd",
    "confirmPassword": "invpswd"
}
